name:                toy
version:             0.1.0.0
github:              "0xd34df00d/toy"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2020 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/toy#readme>

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- data-default
- exceptions
- extra
- interpolate
- megaparsec
- monad-loops
- mtl
- operational
- process
- sexpr-parser
- stm
- temporary
- z3

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  toy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy

tests:
  toy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy
    - hspec
    - QuickCheck
    - QuickCheck-GenT
    - tasty
    - tasty-quickcheck
