resolver: lts-18.18
packages:
- .
extra-deps:
- QuickCheck-GenT-0.2.2
- sexpr-parser-0.2.0.0
#- github: IagoAbal/haskell-z3
#  commit: 93c21e9fa0268430f622d6609b3e395ea26cce58
- github: 0xd34df00d/haskell-z3
  commit: 3abdbb8d09f7104a10673cf6a787ea740fb4ee62
allow-newer: true
